swagger: "2.0"
info: {}
basePath: "/"
tags:
- name: "customers"
paths:
  /customers:
    get:
      tags:
      - "customers"
      summary: "Get all customers"
      description: "Get all customers matching the given search string."
      operationId: "getCustomers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "search"
        in: "query"
        description: "The search string is used to find customer by their name. Not\
          \ case sensetive."
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "Limits the size of the result set"
        required: false
        type: "integer"
        default: "50"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Customer"
    post:
      tags:
      - "customers"
      summary: "Creates a new customer"
      description: "Creates a new customer with the given name. "
      operationId: "createEmployee"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "customer's name"
        required: false
        schema:
          type: "string"
      responses:
        default:
          description: "successful operation"
